# Generated by Django 3.2.4 on 2021-08-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=12, null=True)),
                ('trainer', models.CharField(max_length=20, null=True)),
                ('syllabus', models.TextField(max_length=800, null=True)),
                ('course_duration', models.PositiveSmallIntegerField(null=True)),
                ('course_code', models.CharField(max_length=12, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
