# Generated by Django 3.2.4 on 2021-09-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=18, null=True)),
                ('last_name', models.CharField(max_length=18, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=1, null=True)),
                ('nationality', models.CharField(choices=[('RWANDAN', 'Rwandan'), ('UGANDAN', 'Ugandan'), ('SOUTH SUDANESE', 'South Sudanese'), ('KENYAN', 'Kenyan')], max_length=15, null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
                ('contract', models.FileField(null=True, upload_to='documents/%y/%m/%d')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('salary', models.PositiveBigIntegerField(null=True)),
                ('trainer_id', models.CharField(max_length=20, null=True)),
                ('company', models.CharField(max_length=20, null=True)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('date_hired', models.DateField(null=True)),
            ],
        ),
    ]
