# Generated by Django 3.2.4 on 2021-08-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=12, null=True)),
                ('last_name', models.CharField(max_length=12, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='Female', max_length=30, null=True)),
                ('email', models.EmailField(max_length=22, null=True)),
                ('student_id', models.PositiveSmallIntegerField(null=True)),
                ('nationality', models.CharField(choices=[('Rwandan', 'Rwandan'), ('Ugandan', 'Ugandan'), ('Kenya', 'Kenya')], max_length=18, null=True)),
                ('nationality_id', models.CharField(max_length=20, null=True)),
                ('medical_report', models.FileField(null=True, upload_to='documents/')),
                ('lanquage', models.CharField(max_length=20, null=True)),
                ('laptop_serial_number', models.CharField(max_length=18, null=True)),
                ('date_of_enrollment', models.DateField(null=True)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
