# Generated by Django 3.2.4 on 2021-09-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile',
            new_name='picture',
        ),
    ]
