# Generated by Django 3.2.4 on 2021-09-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_profile_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
